name: CI/CD Pipeline - Frontend

on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Ejecutar script de construcción
        run: |
          chmod +x .github/scripts/build.sh
          ./.github/scripts/build.sh

      - name: Build de la imagen Docker del frontend
        run: |
          docker build -t vue_frontend:latest .
          docker tag vue_frontend:latest vue_frontend:latest

      - name: Save Docker image as artifact
        run: |
          docker save vue_frontend:latest | gzip > vue_frontend-latest.tar.gz

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v2
        with:
          name: vue_frontend-docker-image
          path: vue_frontend-latest.tar.gz
